{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import numpy as np\n",
    "import fabio\n",
    "import networkx as nx\n",
    "from scipy.sparse import csr_matrix\n",
    "from scipy.sparse.csgraph import dijkstra\n",
    "import math\n",
    "import pprint\n",
    "\n",
    "file = 'd25_CeO2-00000.tif'\n",
    "img = fabio.open(file).data\n",
    "\n",
    "\n",
    "#Creates random numpy array for testing\n",
    "test_array = np.random.rand(10,10)\n",
    "\n",
    "def big_function(image):\n",
    "    #Make your own bool array, which will correspond to the bools in the intensity array\n",
    "    bool_array = np.broadcast_to(False, image.shape)\n",
    "\n",
    "\n",
    "    #This will take each pixel coordinate, as a key, and match its corresponding intensity to a value in a dictionary\n",
    "    height_img = image.shape[0]\n",
    "    width_img = image.shape[1]\n",
    "\n",
    "\n",
    "    height_bool = bool_array.shape[0]\n",
    "    width_bool = bool_array.shape[1]\n",
    "\n",
    "    total_coordinates_list = []\n",
    "    intensities_list = []\n",
    "    #Two dictionaries, one with intensities, one with booleans\n",
    "    both_dict = {}\n",
    "    ###Figure out how to make all false firts, thenmove to this part\n",
    "    \n",
    "    def get_image_edges(image):\n",
    "        height, width = image.shape\n",
    "        edge_pixels = []\n",
    "        edge_pixels.extend([(0, y) for y in range(height)])\n",
    "        edge_pixels.extend([(x, 9) for x in range(width)])\n",
    "        edge_pixels.extend([(9, y) for y in range(height)])\n",
    "        edge_pixels.extend([(x, 0) for x in range(width)])\n",
    "        #print(\"These are the edges of your image\", edge_pixels)\n",
    "        return edge_pixels\n",
    "\n",
    "    #Coordinates for intensities\n",
    "    for y in range(height_img) and range (height_bool):\n",
    "        for x in range(width_img) and range(width_bool):\n",
    "            pixel = image.data[x,y]\n",
    "            bool_val = bool_array[x,y]\n",
    "            both_dict.update({(x,y): [bool_val, pixel]})\n",
    "\n",
    "    #print(list(both_dict.items())[1])\n",
    "\n",
    "    values_list = []\n",
    "    values_coordinates = []\n",
    "\n",
    "    def find_start_values(x, y):\n",
    "        starting_bool_and_intensity = both_dict[(x, y)]\n",
    "        values_list.append(starting_bool_and_intensity)\n",
    "        #starting_point = both_dict.keys((x, y))\n",
    "        values_coordinates.append((x, y))\n",
    "\n",
    "        #was getting stuck on flipping the bool value: fixed with smaller_list[0] = not smaller_list[0]\n",
    "        #for smaller_list in values_list:\n",
    "        #    smaller_list[0] = True\n",
    "\n",
    "        #print(values_list)\n",
    "\n",
    "\n",
    "    def getadjacent_pixels(x, y):\n",
    "        good_list = []\n",
    "        a_p = (x-1, y), (x, y-1), (x+1, y), (x, y+1), (x-1, y-1), (x+1, y+1), (x-1, y+1), (x+1, y-1)\n",
    "        \n",
    "        for px, py in a_p:\n",
    "            if 0 <= px < width_img:\n",
    "                if 0 <= py < height_img:\n",
    "                    good_list.append((px, py))\n",
    "                       \n",
    "        return good_list\n",
    "    \n",
    "    shortest_path_point_dictionaries = {}\n",
    "    for edge_starting_point in get_image_edges(image):\n",
    "        #Creates dictionaries to store list of least \n",
    "        shortest_path_point_dictionaries.update({edge_starting_point: []})\n",
    "    \n",
    "\n",
    "    pixels_to_visit = [(np.ceil(height_img/2), np.ceil(width_img/2))]\n",
    "    \n",
    "    every_single_pixel_dictionary = {}\n",
    "    for y in range(height_img) and range (height_bool):\n",
    "        for x in range(width_img) and range(width_bool):\n",
    "            every_single_pixel_dictionary.update({(x, y): [math.inf, []]})\n",
    "    \n",
    "    center_pixel = (np.ceil(height_img/2), np.ceil(width_img/2))\n",
    "    every_single_pixel_dictionary[center_pixel] = [both_dict[center_pixel][1], [center_pixel]]\n",
    "    \n",
    "    while len(pixels_to_visit) > 0:\n",
    "        pixel_xy = pixels_to_visit.pop()\n",
    "        both_dict[pixel_xy][0] = True\n",
    "        path_intensity, path = every_single_pixel_dictionary[pixel_xy]\n",
    "        #print(\"path:\", path, pixel_xy)\n",
    "        #print(\"path intensity\", path_intensity)\n",
    "        \n",
    "        #print(\"this pixel\", pixel[0], pixel[1])\n",
    "        \n",
    "        #This line is producing the None\n",
    "        #print(find_start_values(pixel_xy[0], pixel_xy[1]))\n",
    "        \n",
    "        #Thing in curly braces is interprated as the varriable\n",
    "        #print(f\"pixel = {pixel}\")\n",
    "        adjacents = getadjacent_pixels(pixel_xy[0], pixel_xy[1])\n",
    "        #print(f\"adjacents = {adjacents}\")\n",
    "        \n",
    "        for adjacent_pixel in adjacents:\n",
    "            pixel_value = both_dict[adjacent_pixel]\n",
    "            if pixel_value[0] == False:\n",
    "                pixels_to_visit.append(adjacent_pixel)\n",
    "            intensity_sum = path_intensity + both_dict[adjacent_pixel][1]\n",
    "        \n",
    "            if intensity_sum < every_single_pixel_dictionary[adjacent_pixel][0]:\n",
    "                worst_path = every_single_pixel_dictionary[adjacent_pixel][1]\n",
    "                best_path = path + [adjacent_pixel]\n",
    "                every_single_pixel_dictionary[adjacent_pixel][1] = best_path\n",
    "                every_single_pixel_dictionary[adjacent_pixel][0] = intensity_sum\n",
    "                #print(\"best path\", best_path)\n",
    "                #print(\"intensity for that path:\", intensity_sum)\n",
    "            #else:\n",
    "                #print(\"found a worse path for\", adjacent_pixel)\n",
    "                \n",
    "\n",
    "    adjacent_pixel_coordinates = getadjacent_pixels(np.ceil(height_img/2), np.ceil(width_img/2))\n",
    "    values_coordinates.extend(adjacent_pixel_coordinates)\n",
    "    \n",
    "    #as we go along, math.inf will be replaced by the the sum of the intensities of every pixel in the list\n",
    "    #and the list will be the list will contain the pixel coordinates\n",
    "    \n",
    "    \n",
    "    path_list = []\n",
    "\n",
    "    \n",
    "    #was getting stuck on flipping the bool value: fixed with value[0] = not value[0]\n",
    "    for key, value in both_dict.items():\n",
    "        if key in values_coordinates and value[0] == False:\n",
    "            value[0] = not value[0]\n",
    "\n",
    "    #Some of these repeat at overlapping points\n",
    "    #pprint.pprint(every_single_pixel_dictionary)\n",
    "    #print(every_single_pixel_dictionary.keys())\n",
    "    final_paths_list = []\n",
    "    for q in get_image_edges(image):\n",
    "        if q in every_single_pixel_dictionary.keys():\n",
    "            #print(\"Here are the matching points:\", q)\n",
    "            edge_from_center = every_single_pixel_dictionary[q]\n",
    "            final_paths_list.append(edge_from_center)\n",
    "            #edge_from_center_array = np.array(edge_from_center)\n",
    "            #print(edge_from_center)\n",
    "            \n",
    "            #This can help keep you organized\n",
    "            #print(\"The lowest intensity path to get from center to the edge\", q, \"is\", every_single_pixel_dictionary[q])\n",
    "            \n",
    "    #This list contains the final paths\n",
    "    print(final_paths_list)\n",
    "    \n",
    "            #print(\"The lowest intensity path to get from center to the edge\", q, \"is\", every_single_pixel_dictionary[q])\n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
